### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by podviaznikov** [SvenWoltmann/color-thief-java#2]
Can you push this to Maven?

**Comment by ultimate-tester** [comment]
+1 on this!

**Comment by fuj1w4r4** [comment]
any update on this?

**Comment by SvenWoltmann** [comment]
Sorry—I'll take care of it right away!

**Comment by SvenWoltmann** [comment]
I've uploaded the library to Sonatype OSSRH. It might take a couple of hours until it's available.

**Comment by SvenWoltmann** [comment]
It's available on Maven Central:
http://central.maven.org/maven2/de/androidpit/color-thief/

And on MVNRepository:
https://mvnrepository.com/artifact/de.androidpit/color-thief
