### ISSUE TITLE
Bug in white pixels handling

### ISSUE THREAD

**Issue by tillnagel** [SvenWoltmann/color-thief-java#3]
In the `getPixelsSlow` method (near-)white pixels are not handled correctly, as the condition only checks for the red-value, but not for red, green, blue.

https://github.com/SvenWoltmann/color-thief-java/blob/master/src/main/java/de/androidpit/colorthief/ColorThief.java#L348

**Comment by SvenWoltmann** [comment]
Sorry for the late response. I had an outdated e-mail address in my github account and just noticed that a few days ago when I worked on another github project.

Thanks a lot for pointing out that bug. I just committed a fix to the master branch.
