### ISSUE TITLE
Palette is shorter by 1 then requested

### ISSUE THREAD

**Issue by volgin** [SvenWoltmann/color-thief-java#8]
When you request a palette with 8 colors, the returned array contains 7 colors. The same with any other value - off by 1.

**Comment by suhaylhallim** [comment]
I’m just queuing; is the return array index 0 to 6 which will make it 7 returned colors? Or is it index 0 to 7 because that will make it 8 return colors.

**Comment by SvenWoltmann** [comment]
I can confirm that with a `colorCount >= 8`, the returned array contains only `colorCount - 1` elements. At this moment I cannot say why. I have to dig into the algorithm, but I do not have time to do that before next week.

The returned array is always 0-based, and no matter if colorCount is 7 or 8, it contains 7 elements at positions 0 to 6.

**Comment by SvenWoltmann** [comment]
There was a second bug: for `colorCount <= 3`, the returned array contained `colorCount + 1` elements.

Both bugs have now been fixed.
